services:
  - type: web
    name: mometrix-datahub
    env: python
    runtime: python-3.11
    buildCommand: |
      python -m pip install --upgrade pip setuptools wheel
      python -m pip install -r requirements.txt
      flask init-db --force
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 120 run:app
    autoDeploy: true
    envVars:
      - key: FLASK_CONFIG
        value: "production"



