"""Add subscription tables

Revision ID: f40d4d1a7f40
Revises: a0db97a8af72
Create Date: 2025-05-07 13:00:23.495866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f40d4d1a7f40'
down_revision = 'a0db97a8af72'
branch_labels = None
depends_on = None

# This file should be checked for existence first

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('billing_cycle', sa.String(length=20), nullable=True),
    sa.Column('max_sales', sa.Integer(), nullable=True),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.Column('feature_analytics', sa.Boolean(), nullable=True),
    sa.Column('feature_export', sa.Boolean(), nullable=True),
    sa.Column('feature_premium_tools', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('company_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('current_period_start', sa.DateTime(), nullable=True),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('payment_provider_id', sa.String(length=100), nullable=True),
    sa.Column('sales_count', sa.Integer(), nullable=True),
    sa.Column('user_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_plan_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'subscription_plans', ['subscription_plan_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('subscription_plan_id')

    op.drop_table('company_subscriptions')
    op.drop_table('subscription_plans')
    # ### end Alembic commands ###
