"""Add mailing list table, update roles

Revision ID: f44d0dd18360
Revises: 
Create Date: 2025-05-02 23:38:08.186120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f44d0dd18360'
down_revision = None
branch_labels = None
depends_on = None

# This file should be checked for existence first

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mailing_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('subscribed_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mailing_list', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mailing_list_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mailing_list', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mailing_list_email'))

    op.drop_table('mailing_list')
    # ### end Alembic commands ###
